name: Deploy AA Tool - Sjednocený

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          # Tady používám tvůj název SSH_KEY
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          # Tady používám tvůj název HOST
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
      
      - name: Execute Remote Commands
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            export PATH=$PATH:/usr/bin:/usr/local/bin
            export LD_LIBRARY_PATH=/lib/aarch64-linux-gnu:$LD_LIBRARY_PATH
            cd /root/master-project
            git pull origin main
            # Teď už bez absolutní cesty, ať si to Linux přebere sám
            docker compose up -d --build
          EOF